package com.pulso.app.sensor

import com.pulso.app.tools.ActionKind

internal val HIL_MOTION_ACTIONS = setOf(ActionKind.MOVE_TO, ActionKind.LOOK_AT)

internal val HIL_TERMINAL_STATUSES = setOf(
    "SUCCEEDED",
    "BLOCKED",
    "CANCELLED",
    "REJECTED",
    "TIMEOUT",
    "ACTUATOR_TIMEOUT",
    "BUSY",
    "DUPLICATE_ACTION",
    "INVALID_CONTRACT",
    "INVALID_ACTION_ID",
    "INVALID_MISSION_ID",
    "INVALID_TIMESTAMP",
    "INVALID_ACTION_KIND",
    "INVALID_PARAMETERS",
    "INVALID_TARGET",
    "INVALID_CAPABILITY",
    "STALE_OR_UNKNOWN_TARGET",
    "STALE_CAPABILITY",
    "EXPIRED_CAPABILITY",
    "STALE_NAVIGATION_REVISION",
    "STALE_TRACKING_EPOCH",
    "STALE_TARGET_REVISION",
    "TARGET_TYPE_MISMATCH",
    "TARGET_TOO_CLOSE",
    "ROTATION_ONLY_VIEWPOINT",
    "LOCALIZATION_UNAVAILABLE",
    "UNSUPPORTED_ACTION",
)
